name = "Create-Colony-1.18.2"
author = "Keiichiro UI"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "337d5f11654c621b291cd186a3e53c4a6d464988052c8fd245e7b14cc5f96fb3"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
