name = "Create-Colony-1.18.2"
author = "Keiichiro UI"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e912949b3e19781cdb42313674e6707f6fef61dd870b957f919ca92d456336b3"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
