name = "Create-Colony-1.18.2"
author = "Keiichiro UI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06b93836650c6150fdd0c7e1621bdf8704b4681d508accb038ea658949b69425"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
