name = "Create-Colony-1.18.2"
author = "Keiichiro UI"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "264534bbf015c9609966201b88c6257b772c69d0eeb44b8062584286cd249b3e"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
