name = "Create-Colony-1.18.2"
author = "Keiichiro UI"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3dbf4b5bfbfedee9d7f30b1f21e4570fc31ee63a1a7175394a131f303c6dfb9"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
