name = "Create-Colony-1.18.2"
author = "Keiichiro UI"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "098f65709c8f3d425d7d0fff9d67b7e43d31184a24a4f2b54abaab2fe1b02b49"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
