name = "Create-Colony-1.18.2"
author = "Keiichiro UI"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53bf343d276b4cfda2b9e932d17205df09df8079eee1d9bf1dad5ab0b55a8588"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
